//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 17/03/2013 09:01:48
namespace SticKart.SticKartScores
{
    
    /// <summary>
    /// The database structure and interface mapped to a class.
    /// </summary>
    public partial class SticKartScores_0Entities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new SticKartScores_0Entities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SticKartScores_0Entities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }

        /// <summary>
        /// Runs on the creation of the context.
        /// </summary>
        partial void OnContextCreated();

        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("SticKartScores_0Model", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("SticKart.SticKartScores", typeName.Substring(21)), false);
            }
            return null;
        }

        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("SticKart.SticKartScores", global::System.StringComparison.Ordinal))
            {
                return string.Concat("SticKartScores_0Model.", clientType.Name);
            }
            return null;
        }

        /// <summary>
        /// Gets the elements stored in the high score table.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<HighScore> HighScores
        {
            get
            {
                if ((this._HighScores == null))
                {
                    this._HighScores = base.CreateQuery<HighScore>("HighScores");
                }
                return this._HighScores;
            }
        }

        /// <summary>
        /// The high score table.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<HighScore> _HighScores;

        /// <summary>
        /// Gets the elements stored in the active players table.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ActivePlayer> ActivePlayers
        {
            get
            {
                if ((this._ActivePlayers == null))
                {
                    this._ActivePlayers = base.CreateQuery<ActivePlayer>("ActivePlayers");
                }
                return this._ActivePlayers;
            }
        }

        /// <summary>
        /// The active players table.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ActivePlayer> _ActivePlayers;

        /// <summary>
        /// Gets the elements stored in the statistics table.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Statistic> Statistics
        {
            get
            {
                if ((this._Statistics == null))
                {
                    this._Statistics = base.CreateQuery<Statistic>("Statistics");
                }
                return this._Statistics;
            }
        }

        /// <summary>
        /// The statistics table.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Statistic> _Statistics;

        /// <summary>
        /// Deprecated Method for adding a new object to the HighScores EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToHighScores(HighScore highScore)
        {
            base.AddObject("HighScores", highScore);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the ActivePlayers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToActivePlayers(ActivePlayer activePlayer)
        {
            base.AddObject("ActivePlayers", activePlayer);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the Statistics EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStatistics(Statistic statistic)
        {
            base.AddObject("Statistics", statistic);
        }
    }

    /// <summary>
    /// A high score table entry.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("HighScores")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class HighScore : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new HighScore object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="level">Initial value of Level.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="score">Initial value of Score.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static HighScore CreateHighScore(int ID, int level, string name, int score)
        {
            HighScore highScore = new HighScore();
            highScore.Id = ID;
            highScore.Level = level;
            highScore.Name = name;
            highScore.Score = score;
            return highScore;
        }

        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }

        /// <summary>
        /// The id.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;

        /// <summary>
        /// Runs when the id value is changing.
        /// </summary>
        /// <param name="value">The new value.</param>
        partial void OnIdChanging(int value);

        /// <summary>
        /// Runs when the id value is changed.
        /// </summary>
        partial void OnIdChanged();

        /// <summary>
        /// Gets or sets the level number.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Level
        {
            get
            {
                return this._Level;
            }
            set
            {
                this.OnLevelChanging(value);
                this._Level = value;
                this.OnLevelChanged();
                this.OnPropertyChanged("Level");
            }
        }

        /// <summary>
        /// The level number.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Level;

        /// <summary>
        /// Runs when the level value is changing.
        /// </summary>
        /// <param name="value">The new value.</param>
        partial void OnLevelChanging(int value);

        /// <summary>
        /// Runs when the level value is changed.
        /// </summary>
        partial void OnLevelChanged();

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }

        /// <summary>
        /// The name.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;

        /// <summary>
        /// Runs when the name value is changing.
        /// </summary>
        /// <param name="value">The new value.</param>
        partial void OnNameChanging(string value);

        /// <summary>
        /// Runs when the name value is changed.
        /// </summary>
        partial void OnNameChanged();

        /// <summary>
        /// Gets or sets the score.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Score
        {
            get
            {
                return this._Score;
            }
            set
            {
                this.OnScoreChanging(value);
                this._Score = value;
                this.OnScoreChanged();
                this.OnPropertyChanged("Score");
            }
        }

        /// <summary>
        /// The score.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Score;

        /// <summary>
        /// Runs when the score value is changing.
        /// </summary>
        /// <param name="value">The new value.</param>
        partial void OnScoreChanging(int value);

        /// <summary>
        /// Runs when the score value is changed.
        /// </summary>
        partial void OnScoreChanged();

        /// <summary>
        /// Event handler for a property change event.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Runs when a property is changed.
        /// </summary>
        /// <param name="property">The property.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }

    /// <summary>
    /// Holds details of an active player table entry.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ActivePlayers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class ActivePlayer : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ActivePlayer object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="ip">Initial value of Ip.</param>
        /// <param name="port">Initial value of Port.</param>
        /// <param name="state">Initial value of State.</param>
        /// <param name="player">Initial value of Player.</param>
        /// <param name="session">Initial value of Session.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ActivePlayer CreateActivePlayer(int ID, string ip, string port, string state, int player, int session)
        {
            ActivePlayer activePlayer = new ActivePlayer();
            activePlayer.Id = ID;
            activePlayer.Ip = ip;
            activePlayer.Port = port;
            activePlayer.State = state;
            activePlayer.Player = player;
            activePlayer.Session = session;
            return activePlayer;
        }

        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }

        /// <summary>
        /// The id.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;

        /// <summary>
        /// Runs when the id value is changing.
        /// </summary>
        /// <param name="value">The new value.</param>
        partial void OnIdChanging(int value);

        /// <summary>
        /// Runs when the id value is changed.
        /// </summary>
        partial void OnIdChanged();

        /// <summary>
        /// Gets or sets the ip address.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ip
        {
            get
            {
                return this._Ip;
            }
            set
            {
                this.OnIpChanging(value);
                this._Ip = value;
                this.OnIpChanged();
                this.OnPropertyChanged("Ip");
            }
        }

        /// <summary>
        /// The ip address.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ip;

        /// <summary>
        /// Runs when the ip value is changing.
        /// </summary>
        /// <param name="value">The new value.</param>
        partial void OnIpChanging(string value);

        /// <summary>
        /// Runs when the ip value is changed.
        /// </summary>
        partial void OnIpChanged();

        /// <summary>
        /// Gets or sets the port number.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Port
        {
            get
            {
                return this._Port;
            }
            set
            {
                this.OnPortChanging(value);
                this._Port = value;
                this.OnPortChanged();
                this.OnPropertyChanged("Port");
            }
        }

        /// <summary>
        /// The port number.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Port;

        /// <summary>
        /// Runs when the port value is changing.
        /// </summary>
        /// <param name="value">The new value.</param>
        partial void OnPortChanging(string value);

        /// <summary>
        /// Runs when the port value is changed.
        /// </summary>
        partial void OnPortChanged();

        /// <summary>
        /// Gets or sets the state.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string State
        {
            get
            {
                return this._State;
            }
            set
            {
                this.OnStateChanging(value);
                this._State = value;
                this.OnStateChanged();
                this.OnPropertyChanged("State");
            }
        }

        /// <summary>
        /// The state.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _State;

        /// <summary>
        /// Runs when the state value is changing.
        /// </summary>
        /// <param name="value">The new value.</param>
        partial void OnStateChanging(string value);

        /// <summary>
        /// Runs when the state value is changed.
        /// </summary>
        partial void OnStateChanged();

        /// <summary>
        /// Gets or sets the player number.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Player
        {
            get
            {
                return this._Player;
            }
            set
            {
                this.OnPlayerChanging(value);
                this._Player = value;
                this.OnPlayerChanged();
                this.OnPropertyChanged("Player");
            }
        }

        /// <summary>
        /// The player number.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Player;

        /// <summary>
        /// Runs when the player value is changing.
        /// </summary>
        /// <param name="value">The new value.</param>
        partial void OnPlayerChanging(int value);

        /// <summary>
        /// Runs when the player value is changed.
        /// </summary>
        partial void OnPlayerChanged();

        /// <summary>
        /// Gets or sets the session number.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Session
        {
            get
            {
                return this._Session;
            }
            set
            {
                this.OnSessionChanging(value);
                this._Session = value;
                this.OnSessionChanged();
                this.OnPropertyChanged("Session");
            }
        }

        /// <summary>
        /// The session number.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Session;

        /// <summary>
        /// Runs when the session value is changing.
        /// </summary>
        /// <param name="value">The new value.</param>
        partial void OnSessionChanging(int value);

        /// <summary>
        /// Runs when the session value is changed.
        /// </summary>
        partial void OnSessionChanged();

        /// <summary>
        /// Gets or sets the linked statistic id number.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Statistic Statistic
        {
            get
            {
                return this._Statistic;
            }
            set
            {
                this._Statistic = value;
                this.OnPropertyChanged("Statistic");
            }
        }

        /// <summary>
        /// The linked statistic.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Statistic _Statistic;
        
        /// <summary>
        /// The property changed event handler.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary>
        /// Runs when any property is changed.
        /// </summary>
        /// <param name="property">The property.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }

    /// <summary>
    /// Holds details of a statistic table entry.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Statistics")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Statistic : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Statistic object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="password">Initial value of Password.</param>
        /// <param name="gamesPlayed">Initial value of GamesPlayed.</param>
        /// <param name="gamesWon">Initial value of GamesWon.</param>
        /// <param name="gamesLost">Initial value of GamesLost.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Statistic CreateStatistic(int ID, string name, string password, int gamesPlayed, int gamesWon, int gamesLost)
        {
            Statistic statistic = new Statistic();
            statistic.Id = ID;
            statistic.Name = name;
            statistic.Password = password;
            statistic.GamesPlayed = gamesPlayed;
            statistic.GamesWon = gamesWon;
            statistic.GamesLost = gamesLost;
            return statistic;
        }

        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }

        /// <summary>
        /// The id.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;

        /// <summary>
        /// Runs when the id value is changing.
        /// </summary>
        /// <param name="value">The new value.</param>
        partial void OnIdChanging(int value);

        /// <summary>
        /// Runs when the id value is changed.
        /// </summary>
        partial void OnIdChanged();

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }

        /// <summary>
        /// The name.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;

        /// <summary>
        /// Runs when the name value is changing.
        /// </summary>
        /// <param name="value">The new value.</param>
        partial void OnNameChanging(string value);

        /// <summary>
        /// Runs when the name value is changed.
        /// </summary>
        partial void OnNameChanged();

        /// <summary>
        /// Gets or sets the password.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
                this.OnPropertyChanged("Password");
            }
        }

        /// <summary>
        /// The password.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Password;

        /// <summary>
        /// Runs when the password value is changing.
        /// </summary>
        /// <param name="value">The new value.</param>
        partial void OnPasswordChanging(string value);

        /// <summary>
        /// Runs when the password value is changed.
        /// </summary>
        partial void OnPasswordChanged();

        /// <summary>
        /// Gets or sets the number of games played.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int GamesPlayed
        {
            get
            {
                return this._GamesPlayed;
            }
            set
            {
                this.OnGamesPlayedChanging(value);
                this._GamesPlayed = value;
                this.OnGamesPlayedChanged();
                this.OnPropertyChanged("GamesPlayed");
            }
        }

        /// <summary>
        /// The number of games played.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _GamesPlayed;

        /// <summary>
        /// Runs when the games played value is changing.
        /// </summary>
        /// <param name="value">The new value.</param>
        partial void OnGamesPlayedChanging(int value);

        /// <summary>
        /// Runs when the games played value is changed.
        /// </summary>
        partial void OnGamesPlayedChanged();

        /// <summary>
        /// Gets or sets the number of games won.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int GamesWon
        {
            get
            {
                return this._GamesWon;
            }
            set
            {
                this.OnGamesWonChanging(value);
                this._GamesWon = value;
                this.OnGamesWonChanged();
                this.OnPropertyChanged("GamesWon");
            }
        }

        /// <summary>
        /// The number of games won.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _GamesWon;

        /// <summary>
        /// Runs when the games won value is changing.
        /// </summary>
        /// <param name="value">The new value.</param>
        partial void OnGamesWonChanging(int value);

        /// <summary>
        /// Runs when the games won value is changed.
        /// </summary>
        partial void OnGamesWonChanged();

        /// <summary>
        /// Gets or sets the number of games lost.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int GamesLost
        {
            get
            {
                return this._GamesLost;
            }
            set
            {
                this.OnGamesLostChanging(value);
                this._GamesLost = value;
                this.OnGamesLostChanged();
                this.OnPropertyChanged("GamesLost");
            }
        }

        /// <summary>
        /// The number of games lost.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _GamesLost;

        /// <summary>
        /// Runs when the games lost value is changing.
        /// </summary>
        /// <param name="value">The new value.</param>
        partial void OnGamesLostChanging(int value);

        /// <summary>
        /// Runs when the games lost value is changed.
        /// </summary>
        partial void OnGamesLostChanged();

        /// <summary>
        /// Gets or sets the active players table which references the statistic.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<ActivePlayer> ActivePlayers
        {
            get
            {
                return this._ActivePlayers;
            }
            set
            {
                this._ActivePlayers = value;
                this.OnPropertyChanged("ActivePlayers");
            }
        }

        /// <summary>
        /// The active players table which references the statistic.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<ActivePlayer> _ActivePlayers = new global::System.Data.Services.Client.DataServiceCollection<ActivePlayer>(null, System.Data.Services.Client.TrackingMode.None);
        
        /// <summary>
        /// An event handler for a property changed event.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Runs when a property is changed.
        /// </summary>
        /// <param name="property">The property.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
