CREATE TABLE [dbo].[HighScores_000]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] CHAR(10) NOT NULL,
	[Score] INT NOT NULL
)
GO
CREATE TABLE [dbo].[HighScores_001]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] CHAR(10) NOT NULL,
	[Score] INT NOT NULL
)
GO
CREATE TABLE [dbo].[HighScores_002]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] CHAR(10) NOT NULL,
	[Score] INT NOT NULL
)
GO
CREATE TABLE [dbo].[HighScores_003]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] CHAR(10) NOT NULL,
	[Score] INT NOT NULL
)
GO
CREATE TABLE [dbo].[HighScores_004]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] CHAR(10) NOT NULL,
	[Score] INT NOT NULL
)
GO
CREATE TABLE [dbo].[HighScores_005]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] CHAR(10) NOT NULL,
	[Score] INT NOT NULL
)
GO
CREATE TABLE [dbo].[HighScores_006]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] CHAR(10) NOT NULL,
	[Score] INT NOT NULL
)
GO
CREATE TABLE [dbo].[HighScores_007]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] CHAR(10) NOT NULL,
	[Score] INT NOT NULL
)
GO
CREATE TABLE [dbo].[HighScores_008]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] CHAR(10) NOT NULL,
	[Score] INT NOT NULL
)
GO
CREATE TABLE [dbo].[HighScores_009]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] CHAR(10) NOT NULL,
	[Score] INT NOT NULL
)
GO
CREATE TABLE [dbo].[HighScores_010]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] CHAR(10) NOT NULL,
	[Score] INT NOT NULL
)