// <auto-generated />

using System;
using System.Diagnostics;
using System.IO;
using Microsoft.WindowsAzure.Diagnostics;
using Microsoft.WindowsAzure.ServiceRuntime;

namespace SticKartScoresAzureWebRole
{
    /// <summary>
    /// A trace listener for logging errors.
    /// </summary>
    public class AzureLocalStorageTraceListener : XmlWriterTraceListener
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AzureLocalStorageTraceListener"/> class.
        /// </summary>
        public AzureLocalStorageTraceListener()
            : base(Path.Combine(AzureLocalStorageTraceListener.GetLogDirectory().Path, "SticKartScoresAzureWebRole.svclog"))
        {
        }

        /// <summary>
        /// Retrieves the trace log directory.
        /// </summary>
        /// <returns>The trace log directory</returns>
        public static DirectoryConfiguration GetLogDirectory()
        {
            DirectoryConfiguration directory = new DirectoryConfiguration();
            directory.Container = "wad-tracefiles";
            directory.DirectoryQuotaInMB = 10;
            directory.Path = RoleEnvironment.GetLocalResource("SticKartScoresAzureWebRole.svclog").RootPath;
            return directory;
        }
    }
}
